### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by NordicGamerFE** [SnowShock35/jei-integration#5]
I dont know if this error has anything to do with this mod or a other mod but you might be able to point be in the correct direction if its not, So i get this issue in the console along with some lag spikes

Modpack: Ocean Outlast v.52
Mod: jeiintegration_1.12.2-1.6.0

Error:
`Mod added a tree entry after memory optimization!
java.lang.UnsupportedOperationException
	at it.unimi.dsi.fastutil.chars.AbstractChar2ObjectFunction.put(AbstractChar2ObjectFunction.java:119)
	at mezz.jei.suffixtree.Node.addEdge(Node.java:124)
	at mezz.jei.suffixtree.GeneralizedSuffixTree.update(GeneralizedSuffixTree.java:335)
	at mezz.jei.suffixtree.GeneralizedSuffixTree.put(GeneralizedSuffixTree.java:166)
	at mezz.jei.ingredients.IngredientFilter.addIngredient(IngredientFilter.java:119)
	at mezz.jei.ingredients.IngredientRegistry.addIngredientsAtRuntime(IngredientRegistry.java:277)
	at mezz.jei.ingredients.IngredientRegistry.addIngredientsAtRuntime(IngredientRegistry.java:222)
	at mezz.jei.ingredients.IngredientRegistry.addIngredientsAtRuntime(IngredientRegistry.java:229)
	at li.cil.oc.integration.jei.ModJEI$$anonfun$addDiskAtRuntime$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.apply(ModJEI.scala:27)
	at li.cil.oc.integration.jei.ModJEI$$anonfun$addDiskAtRuntime$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$1.apply(ModJEI.scala:27)
	at scala.Option.foreach(Option.scala:245)
	at li.cil.oc.integration.jei.ModJEI$$anonfun$addDiskAtRuntime$1$$anonfun$apply$1.apply$mcV$sp(ModJEI.scala:27)
	at li.cil.oc.common.EventHandler$$anonfun$onClientTick$1.apply(EventHandler.scala:239)
	at li.cil.oc.common.EventHandler$$anonfun$onClientTick$1.apply(EventHandler.scala:238)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at li.cil.oc.common.EventHandler$.onClientTick(EventHandler.scala:238)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3091_EventHandler$_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

Sorry if this is not the right place for this issue

**Comment by SnowShock35** [comment]
Hi there,

I believe this is an issue with JEI not JEI Integration. I would suggest reporting it over on their [GitHub Repository](https://github.com/mezz/justenoughitems/). Hope this helps. 😄
